added some fixes
BereketRetta/Jest_Todolist pull request #2
Opened 2022-01-27 18:33 UTC by BereketRetta

Add some fixes and files

2022-01-27 21:08 UTC, MrBrN197 requested changes
## Hi, @BereketRetta  👋  

You've done a really nice job so far.
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-27 21:08 UTC, MrBrN197 commented on src/index.js
>      removeComleted();
- [ ] you have the required test but please ensure that they are passing. In the case of your tests, it looks like you have to mock the `localStorage` please make this change. the point of testing is to ensure that your code functions as expected so you need to ensure your tests are always passing.   
![image](https://user-images.githubusercontent.com/18730106/151443754-c61de7c6-29e8-4cbb-8e45-b59b847591b1.png)

2022-01-28 03:50 UTC, BereketRetta commented
<img width="740" alt="Screen Shot 2022-01-28 at 6 50 08 AM" src="https://user-images.githubusercontent.com/47314387/151484161-55a115dc-28b6-4eb1-9c37-ead7a49e5839.png">

It's passing all the required tests

2022-01-28 03:54 UTC, Rustamxon7 approved these changes
## Hi @BereketRetta 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 🎉 🎉 🎉 🎉 

Cheers and Happy coding!👏👏👏

![image](https://i.pinimg.com/originals/77/0e/b0/770eb057449582c44672b2d2d1cc39b6.gif)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-01-28 04:07 UTC, merged